name: Deploy patdilet-web

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Necesario para emular diferentes arquitecturas (amd64, arm64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 2. Setup de Buildx (motor de construcción avanzado para multi-arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Construcción multi-arquitectura
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Aquí especificamos que cree la imagen tanto para tu Mac (arm64) como para tu servidor (amd64)
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/patdilet-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max